<?php
/**
 * Created by IntelliJ IDEA.
 * User: apex
 * Date: 18/04/17
 * Time: 10:19 AM
 */

namespace frontend\models;

use common\models\Brand as BaseBrand;
use yii\db\ActiveQuery;

class Brand extends BaseBrand
{

    /**
     * @return ActiveQuery
     */
    public static function find()
    {
        return new BrandQuery(get_called_class());
    }

}

class BrandQuery extends ActiveQuery
{
    public function init()
    {
        $this->andOnCondition(['visible' => true]);
        parent::init(); // TODO: Change the autogenerated stub
    }

}